# basic configuration
baseurl:
markdown: kramdown
permalink: /:categories/:title/
# Code highlighting
highlighter: rouge


# Change this tracking code with your own tracking code
ga_tracking_code: UA-97628342-1
# Please leave this code here for us to see how Course in a Box get used
p2pu_ga_tracking_code: UA-55722824-1


# Some files we need to exclude, so Github can build the site
exclude: [Gemfile, Gemfile.lock, README.md]

defaults:
  -
    scope:
      path: "modules" # an empty string here means all files in the project
    values:
      layout: "course_page"

prose:
  media: img
  ignore:
    - /_includes
    - /_layouts
    - /_sass
    - /fonts
    - /js
    - /css

# Set some personal styles and logo for your course
# this is a hex value http://www.w3schools.com/tags/ref_colorpicker.asp
jumbotron_color: "#570D1F"
jumbotron_background_image: "header.svg"
jumbotron_image: "MART_LOGO_SMALL.png"

theme: jekyll-theme-slate
